#!/bin/sh
set -e

BOOTSTRAPPED="/etc/postfix/.bootstrapped"

if [ ! -e $BOOTSTRAPPED ]; then
	cat <<-EOF | /etc/postfix/main.cf
	queue_directory = /var/spool/postfix
	data_directory = /var/db/postfix
	mail_owner = postfix

	myhostname = ${MYHOSTNAME}
	mydomain = ${MYDOMAIN}

	myorigin = $mydomain
	mydestination = localhost
	mynetworks = ${MYNETWORKS}
	relay_domains =
	relay_host =

	recipient_delimiter = +
	mailbox_size_limit = 0
	inet_interfaces = all

	smtpd_banner = $myhostname ESMTP $mail_name

	virtual_mailbox_domains = proxy:ldap:$config_directory/ldap_virtual_domains_maps.cf
	virtual_mailbox_maps = proxy:ldap:$config_directory/ldap_virtual_mailbox_maps.cf
	virtual_alias_maps = proxy:ldap:$config_directory/ldap_virtual_alias_maps.cf
	smtpd_sender_login_maps = proxy:ldap:$config_directory/ldap_smtpd_sender_login_maps.cf

	virtual_transport = lmtp:inet:${DOVECOT_HOST}:2424
	smtpd_sender_restrictions = reject_sender_login_mismatch,reject_unknown_sender_domain
	EOF

	cat <<-EOF | /etc/postfix/master.cf
	smtp      inet  n       -       n       -       -       smtpd
		-o content_filter=scan:10.10.10.10:10025
	submission inet n       -       n       -       -       smtpd
		-o syslog_name=postfix/submission
		-o smtpd_tls_wrappermode=no
		-o smtpd_tls_security_level=encrypt
		-o smtpd_sasl_auth_enable=yes
		-o smtpd_client_restrictions=permit_sasl_authenticated,reject
		-o smtpd_recipient_restrictions=permit_sasl_authenticated,reject
		-o smtpd_sasl_type=dovecot
		-o smtpd_sasl_path=inet:${DOVECOT_HOST}:12345
		-o smtpd_tls_CAfile=/etc/ssl/postfix/${SSL_CA}
		-o smtpd_tls_cert_file=/etc/ssl/postfix/${SSL_CERT}
		-o smtpd_tls_key_file=/etc/ssl/postfix/${SSL_KEY}
		-o smtpd_tls_protocols=!SSLv2,!SSLv3
	pickup    unix  n       -       -       60      1       pickup
	cleanup   unix  n       -       -       -       0       cleanup
	qmgr      unix  n       -       n       300     1       qmgr
	#qmgr     unix  n       -       n       300     1       oqmgr
	tlsmgr    unix  -       -       -       1000?   1       tlsmgr
	rewrite   unix  -       -       -       -       -       trivial-rewrite
	bounce    unix  -       -       -       -       0       bounce
	defer     unix  -       -       -       -       0       bounce
	trace     unix  -       -       -       -       0       bounce
	verify    unix  -       -       -       -       1       verify
	flush     unix  n       -       -       1000?   0       flush
	proxymap  unix  -       -       n       -       -       proxymap
	proxywrite unix -       -       n       -       1       proxymap
	smtp      unix  -       -       -       -       -       smtp
	relay     unix  -       -       -       -       -       smtp
	#       -o smtp_helo_timeout=5 -o smtp_connect_timeout=5
	showq     unix  n       -       -       -       -       showq
	error     unix  -       -       -       -       -       error
	retry     unix  -       -       -       -       -       error
	discard   unix  -       -       -       -       -       discard
	local     unix  -       n       n       -       -       local
	virtual   unix  -       n       n       -       -       virtual
	lmtp      unix  -       -       -       -       -       lmtp
	anvil     unix  -       -       -       -       1       anvil
	scache    unix  -       -       -       -       1       scache

	maildrop  unix  -       n       n       -       -       pipe
		flags=DRhu user=vmail argv=/usr/bin/maildrop -d ${recipient}

	uucp      unix  -       n       n       -       -       pipe
		flags=Fqhu user=uucp argv=uux -r -n -z -a$sender - $nexthop!rmail ($recipient)
	ifmail    unix  -       n       n       -       -       pipe
		flags=F user=ftn argv=/usr/lib/ifmail/ifmail -r $nexthop ($recipient)
	bsmtp     unix  -       n       n       -       -       pipe
		flags=Fq. user=bsmtp argv=/usr/lib/bsmtp/bsmtp -t$nexthop -f$sender $recipient
	scalemail-backend unix  -       n       n       -       2       pipe
		flags=R user=scalemail argv=/usr/lib/scalemail/bin/scalemail-store ${nexthop} ${user} ${extension}
	mailman   unix  -       n       n       -       -       pipe
		flags=FR user=list argv=/usr/lib/mailman/bin/postfix-to-mailman.py
		${nexthop} ${user}
	EOF

	cat <<-EOF | ldap_virtual_domains_maps.cf
	server_host = ldap://${LDAP_HOST}
	search_base = ${LDAP_SEARCH_BASE}
	version = 3
	bind = no
	query_filter = (&(objectclass=inetLocalMailRecipient)(mailHost=%s))
	result_attribute = mailHost
	EOF

	cat <<-EOF | ldap_virtual_mailbox_maps.cf
	server_host = ldap://${LDAP_HOST}
	search_base = ${LDAP_SEARCH_BASE}
	version = 3
	bind = no
	query_filter = (&(objectclass=inetOrgPerson)(objectclass=inetLocalMailRecipient)(mail=%s))
	result_attribute = mail
	EOF

	cat <<-EOF | ldap_virtual_alias_maps.cf
	server_host = ldap://${LDAP_HOST}
	search_base = ${LDAP_SEARCH_BASE}
	version = 3
	bind = no
	query_filter = (&(objectclass=inetOrgPerson)(objectclass=inetLocalMailRecipient)(mailLocalAddress=%s))
	result_attribute = mail
	EOF

	cat <<-EOF | ldap_smtpd_sender_login_maps.cf
	server_host = ldap://${LDAP_HOST}
	search_base = ${LDAP_SEARCH_BASE}
	version = 3
	bind = no
	query_filter = (&(objectclass=inetOrgPerson)(objectclass=inetLocalMailRecipient)(mailLocalAddress=%s))
	result_attribute = mail
	EOF

	touch $BOOTSTRAPPED;
fi

exec /usr/lib/postfix/master
